# Generated by Django 4.1.3 on 2022-11-21 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('honorific', models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs')], default='Mr', max_length=8)),
                ('f_name', models.CharField(max_length=40)),
                ('l_name', models.CharField(max_length=40, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('Other', 'Other')], default='Male', max_length=20)),
                ('dob', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country_code', models.CharField(max_length=5, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('country', models.CharField(max_length=40, null=True)),
                ('state', models.CharField(max_length=40, null=True)),
                ('city', models.CharField(max_length=40, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('pin_code', models.CharField(max_length=10, null=True)),
                ('skills', models.CharField(max_length=400, null=True)),
                ('hobbies', models.CharField(max_length=400, null=True)),
                ('interests', models.CharField(max_length=400, null=True)),
                ('image', models.ImageField(null=True, upload_to='Candidate')),
            ],
            options={
                'verbose_name_plural': 'Personal Details',
            },
        ),
        migrations.CreateModel(
            name='EducationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('School', 'School'), ('College', 'College'), ('University', 'University'), ('Institute', 'Institute')], default='School', max_length=40)),
                ('school_name', models.CharField(max_length=400, null=True)),
                ('course', models.CharField(max_length=100, null=True)),
                ('year_of_passing', models.CharField(max_length=20, null=True)),
                ('complited', models.BooleanField(default=False)),
                ('personal_detail', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.personaldetails')),
            ],
            options={
                'verbose_name_plural': 'Education Details',
            },
        ),
    ]
